version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - ./:/usr/src/four_hours_service/
    volumes:
      # - static_volume:/home/app/four_hours_service/staticfiles/
      - static_volume:/usr/src/four_hours_service/staticfiles/
      # - media_volume:/home/app/django/mediafiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file: ${ENVFILE}
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      # - static_volume:/home/app/four_hours_service/staticfiles/
      - static_volume:/usr/src/four_hours_service/staticfiles/
      # - media_volume:/home/app/django/mediafiles
    ports:
      - 1337:80
    depends_on:
      - django

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}

volumes:
  postgres_data:
  static_volume:
