version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/settings.conf:/etc/nginx/settings.conf
      - static_volume:/usr/src/four_hours_service/staticfiles/
    depends_on:
      - django
      - db

  django:
    container_name: django
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/four_hours_service/staticfiles/
    expose:
      - 8000
    env_file: ${ENVFILE}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}

volumes:
  postgres_data:
  static_volume:
