version: '3'

services:
  web:
    build: ./four_hours
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./four_hours/:/usr/src/four_hours/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=four_hours_dev
      - POSTGRES_USER=Lukaid
      - POSTGRES_PASSWORD=bilp1234

volumes:
  postgres_data:
