# pull official base image
FROM python:3.11.2-alpine

# create directory for the app user
RUN mkdir -p /usr/src

# create the appropriate directories
ENV HOME=/usr/src
ENV APP_HOME=/usr/src/four_hours_service
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# #set work directory
# WORKDIR /usr/src/four_hours_service

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev linux-headers

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/four_hours_service/entrypoint.sh
RUN chmod +x /usr/src/four_hours_service/entrypoint.sh

# add four_hours_service
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/four_hours_service/entrypoint.sh"]
