version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - ${ENTRY_PORT}:${ENTRY_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/settings.conf:/etc/nginx/settings.conf
      - static_volume:/usr/src/four_hours_service/staticfiles/
    depends_on:
      - django
      - db
    networks:
      - test

  django:
    container_name: django
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}
    volumes:
      - static_volume:/usr/src/four_hours_service/staticfiles/
    expose:
      - ${DJANGO_PORT}
    env_file: ${ENVFILE}
    depends_on:
      - db
    networks:
      - test

  db:
    container_name: db
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${SQL_PORT}
    ports:
      - "${SQL_PORT}:${SQL_PORT}"
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    command: -p ${SQL_PORT}
    networks:
      - test

volumes:
  postgres_data:
  static_volume:

networks:
  test:
    driver: bridge