# Generated by Django 4.2 on 2023-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=100)),
                ("is_used", models.BooleanField(default=False)),
                ("topic_used_at", models.DateTimeField(null=True)),
                ("is_use", models.BooleanField(default=True)),
            ],
            options={
                "default_related_name": "topics",
            },
        ),
    ]
