# Generated by Django 4.2 on 2023-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_topic_is_generated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("entertainment", "Entertainment"),
                            ("etc", "Etc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("url", models.URLField()),
            ],
            options={
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("job", "Job"),
                            ("gender", "Gender"),
                            ("age", "Age"),
                            ("tone", "Tone"),
                            ("situation", "Situation"),
                            ("characteristic", "Characteristic"),
                            ("topic", "Topic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "default_related_name": "personas",
            },
        ),
    ]
