# Generated by Django 4.2 on 2023-05-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0004_alter_article_options_alter_article_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostGenerated",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("time_taken", models.FloatField(blank=True, null=True)),
                ("total_token", models.IntegerField(blank=True, null=True)),
                ("is_failed", models.BooleanField(default=False)),
                (
                    "persona_age",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_age",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_characteristic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_characteristic",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_gender",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_job",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_situation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_situation",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_tone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_tone",
                        to="resources.persona",
                    ),
                ),
                (
                    "persona_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persona_topic",
                        to="resources.persona",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resources.topic",
                    ),
                ),
            ],
            options={
                "default_related_name": "post_generateds",
            },
        ),
    ]
