# Generated by Django 4.2 on 2023-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0007_article_is_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonaCharacteristic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
            ],
            options={
                "default_related_name": "persona_characteristics",
            },
        ),
        migrations.CreateModel(
            name="PersonaJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
            ],
            options={
                "default_related_name": "persona_jobs",
            },
        ),
        migrations.CreateModel(
            name="PersonaPreset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("10s", "10s"),
                            ("20s", "20s"),
                            ("30s", "30s"),
                            ("40s", "40s"),
                            ("50s", "50s"),
                            ("60s", "60s"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=20
                    ),
                ),
                ("job", models.CharField(blank=True, max_length=100, null=True)),
                ("tone", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "characteristic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "default_related_name": "persona_presets",
            },
        ),
        migrations.CreateModel(
            name="PersonaSituation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
            ],
            options={
                "default_related_name": "persona_situations",
            },
        ),
        migrations.CreateModel(
            name="PersonaTone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=100)),
            ],
            options={
                "default_related_name": "persona_tones",
            },
        ),
    ]
