# Generated by Django 4.2 on 2023-05-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_personacharacteristic_personajob_personapreset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personapreset",
            name="characteristic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_presets",
                to="resources.personacharacteristic",
            ),
        ),
        migrations.AlterField(
            model_name="personapreset",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_presets",
                to="resources.personajob",
            ),
        ),
        migrations.AlterField(
            model_name="personapreset",
            name="tone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_presets",
                to="resources.personatone",
            ),
        ),
    ]
