# Generated by Django 4.2 on 2023-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_alter_personapreset_characteristic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personapreset",
            name="characteristic",
        ),
        migrations.AddField(
            model_name="personapreset",
            name="characteristic",
            field=models.ManyToManyField(
                blank=True,
                related_name="persona_presets",
                to="resources.personacharacteristic",
            ),
        ),
    ]
