# Generated by Django 4.2 on 2023-05-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0010_remove_personapreset_characteristic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_age",
        ),
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_characteristic",
        ),
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_gender",
        ),
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_job",
        ),
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_tone",
        ),
        migrations.RemoveField(
            model_name="postgenerated",
            name="persona_topic",
        ),
        migrations.AddField(
            model_name="postgenerated",
            name="persona_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources.personapreset",
            ),
        ),
        migrations.AlterField(
            model_name="personapreset",
            name="age",
            field=models.CharField(
                choices=[
                    ("10대", "10대"),
                    ("20대", "20대"),
                    ("30대", "30대"),
                    ("40대", "40대"),
                    ("50대", "50대"),
                    ("60대", "60대"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personapreset",
            name="gender",
            field=models.CharField(choices=[("남성", "남성"), ("여성", "여성")], max_length=20),
        ),
        migrations.AlterField(
            model_name="postgenerated",
            name="persona_situation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_situation",
                to="resources.personasituation",
            ),
        ),
    ]
