# Generated by Django 4.2 on 2023-05-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0011_remove_postgenerated_persona_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postgenerated",
            name="persona_preset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_presets",
                to="resources.personapreset",
            ),
        ),
        migrations.AlterField(
            model_name="postgenerated",
            name="persona_situation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persona_situations",
                to="resources.personasituation",
            ),
        ),
    ]
