# Generated by Django 4.2 on 2023-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0012_alter_postgenerated_persona_preset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personapreset",
            name="article_kind",
            field=models.CharField(
                choices=[("sports", "Sports"), ("entertainment", "Entertainment")],
                default="sports",
                max_length=20,
            ),
        ),
    ]
