# Generated by Django 4.2 on 2023-05-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0013_personapreset_article_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="is_used",
            new_name="is_summary",
        ),
        migrations.CreateModel(
            name="ArticleSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("entertainment", "Entertainment"),
                            ("etc", "Etc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary_content", models.TextField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_summaries",
                        to="resources.article",
                    ),
                ),
            ],
            options={
                "default_related_name": "article_summaries",
            },
        ),
    ]
