# Generated by Django 4.2 on 2023-05-24 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "resources",
            "0015_articlesummary_is_failed_articlesummary_time_taken_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesummary",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="articlesummary",
            name="title",
        ),
    ]
