# Generated by Django 4.2 on 2023-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0016_remove_articlesummary_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postgenerated",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
