# Generated by Django 4.2 on 2023-05-31 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0017_alter_postgenerated_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postgenerated",
            old_name="is_active",
            new_name="is_checked",
        ),
        migrations.AddField(
            model_name="postgenerated",
            name="is_accepted",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postgenerated",
            name="who_checked",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
