# Generated by Django 4.2 on 2023-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0018_rename_is_active_postgenerated_is_checked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postgenerated",
            name="is_posted",
            field=models.BooleanField(default=False),
        ),
    ]
