# Generated by Django 4.2 on 2023-07-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0019_postgenerated_is_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="content",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
