# Generated by Django 4.1.7 on 2023-03-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(default="", max_length=150),
        ),
    ]
