# Generated by Django 4.2 on 2023-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_deleted_at_post_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
