# Generated by Django 4.2 on 2023-04-28 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="device",
            new_name="social",
        ),
    ]
