# Generated by Django 4.2 on 2023-04-17 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="uuid",
            new_name="uid",
        ),
    ]
