# Generated by Django 4.2 on 2023-04-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
