# Generated by Django 4.2 on 2023-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_uuid_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
