# Generated by Django 4.2 on 2023-04-28 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_device_usersession_social"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="logged_in_at",
            new_name="issued_at",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="is_expired",
        ),
    ]
