# Generated by Django 4.2 on 2023-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_session_expired_time_usersession_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="issued_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
