# Generated by Django 4.2 on 2023-04-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_picture",
            field=models.URLField(blank=True, default="", max_length=255, null=True),
        ),
    ]
