# Generated by Django 4.2 on 2023-06-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_usersession_auth_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
