# Generated by Django 4.2 on 2023-04-19 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postobscured",
            options={"default_related_name": "post_obscureds"},
        ),
        migrations.AddField(
            model_name="postobscured",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="obscured_content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="posts.post"
            ),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_use",
            field=models.BooleanField(default=True),
        ),
    ]
