# Generated by Django 4.2 on 2023-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_postobscured_options_postobscured_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_obscured",
            field=models.BooleanField(default=False),
        ),
    ]
