# Generated by Django 4.2 on 2023-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_postdeletereason_id_alter_postlike_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postobscured",
            name="is_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="time_taken",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postobscured",
            name="total_token",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
