# Generated by Django 4.2 on 2023-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_postreceipt_is_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postreceipt",
            old_name="is_valid",
            new_name="is_postable",
        ),
        migrations.AddField(
            model_name="postreceipt",
            name="is_readable",
            field=models.BooleanField(default=False),
        ),
    ]
