# Generated by Django 4.2 on 2023-05-06 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_rename_is_valid_postreceipt_is_postable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postreceipt",
            old_name="next_post_available_at",
            new_name="postable_at",
        ),
        migrations.RenameField(
            model_name="postreceipt",
            old_name="shared_post_available_at",
            new_name="readable_ended_at",
        ),
    ]
