# Generated by Django 4.2 on 2023-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "posts",
            "0008_rename_next_post_available_at_postreceipt_postable_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreceipt",
            name="is_postable",
            field=models.BooleanField(default=True),
        ),
    ]
