# Generated by Django 4.2 on 2023-05-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
