# Generated by Django 4.2 on 2023-05-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_post_generated_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="obscured_fail",
            field=models.BooleanField(default=False),
        ),
    ]
